import type { Behavior } from '../types';

export const BEHAVIORS: Behavior[] = [
  {
    id: 'scroll_videos',
    name: '刷短视频',
    emoji: '📱',
    category: 'entertainment',
    effect: { dopamine: 20, stress: 5, attention: -15, fatigue: 5 },
    dynamicEffect: {
      dopamine: {
        type: 'proportional',
        base: 10,
        factor: 0.25,
      },
      attention: {
        type: 'contextual',
        base: -12,
        factor: -0.1,
        dependsOn: 'dopamine',
        condition: (m) => m.dopamine > 60,
      },
      stress: {
        type: 'contextual',
        base: 3,
        factor: 0.15,
        dependsOn: 'fatigue',
      },
      fatigue: {
        type: 'proportional',
        base: 3,
        factor: 0.1,
      },
    },
    durationHours: 0.5,
    description: '多巴胺↑ 注意力↓ 边际效应递减',
  },
  {
    id: 'study',
    name: '学习',
    emoji: '📚',
    category: 'growth',
    effect: { dopamine: 5, stress: 10, attention: 20, fatigue: 10 },
    dynamicEffect: {
      attention: {
        type: 'contextual',
        base: 15,
        factor: 0.2,
        dependsOn: 'dopamine',
        condition: (m) => m.fatigue < 70,
      },
      stress: {
        type: 'contextual',
        base: 8,
        factor: 0.15,
        dependsOn: 'attention',
        condition: (m) => m.attention > 50,
      },
      dopamine: {
        type: 'proportional',
        base: 3,
        factor: 0.05,
      },
      fatigue: {
        type: 'contextual',
        base: 8,
        factor: 0.2,
        dependsOn: 'stress',
      },
    },
    durationHours: 2,
    description: '注意力↑ 压力↑ 效果取决于当前状态',
  },
  {
    id: 'exercise',
    name: '运动',
    emoji: '🏃',
    category: 'physiology',
    effect: { dopamine: 10, stress: -5, attention: 10, fatigue: 15 },
    dynamicEffect: {
      dopamine: {
        type: 'proportional',
        base: 8,
        factor: 0.15,
      },
      stress: {
        type: 'contextual',
        base: -8,
        factor: -0.25,
        dependsOn: 'stress',
        condition: (m) => m.stress > 40,
      },
      fatigue: {
        type: 'contextual',
        base: 12,
        factor: 0.15,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue < 80,
      },
      attention: {
        type: 'proportional',
        base: 8,
        factor: 0.1,
      },
    },
    durationHours: 1,
    description: '多巴胺↑ 压力↓ 疲劳↑',
  },
  {
    id: 'coffee',
    name: '喝咖啡',
    emoji: '☕',
    category: 'physiology',
    effect: { dopamine: 5, stress: 15, attention: 15, fatigue: -10 },
    dynamicEffect: {
      attention: {
        type: 'contextual',
        base: 12,
        factor: -0.15,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue > 30,
      },
      fatigue: {
        type: 'contextual',
        base: -8,
        factor: -0.2,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue > 40,
      },
      stress: {
        type: 'proportional',
        base: 10,
        factor: 0.15,
      },
      dopamine: {
        type: 'proportional',
        base: 5,
        factor: 0.05,
      },
    },
    durationHours: 0.25,
    description: '注意力↑ 疲劳↓ 压力↑ 耐受递减',
  },
  {
    id: 'sleep',
    name: '睡觉',
    emoji: '😴',
    category: 'physiology',
    effect: { dopamine: -5, stress: -15, attention: 10, fatigue: -25 },
    dynamicEffect: {
      fatigue: {
        type: 'contextual',
        base: -20,
        factor: -0.4,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue > 50,
      },
      stress: {
        type: 'contextual',
        base: -12,
        factor: -0.3,
        dependsOn: 'stress',
        condition: (m) => m.stress > 40,
      },
      dopamine: {
        type: 'contextual',
        base: -3,
        factor: 0.0,
        dependsOn: 'dopamine',
        condition: (m) => m.dopamine > 60,
      },
      attention: {
        type: 'contextual',
        base: 10,
        factor: 0.2,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue < 40,
      },
    },
    durationHours: 8,
    description: '疲劳↓↓ 压力↓ 睡眠修复效果显著',
  },
  {
    id: 'stay_up',
    name: '熬夜',
    emoji: '🌙',
    category: 'physiology',
    effect: { dopamine: 10, stress: 20, attention: -20, fatigue: 20 },
    dynamicEffect: {
      fatigue: {
        type: 'contextual',
        base: 15,
        factor: 0.35,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue > 50,
      },
      stress: {
        type: 'contextual',
        base: 15,
        factor: 0.25,
        dependsOn: 'stress',
        condition: (m) => m.stress > 50,
      },
      attention: {
        type: 'contextual',
        base: -15,
        factor: -0.2,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue > 60,
      },
      dopamine: {
        type: 'contextual',
        base: 8,
        factor: -0.1,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue < 70,
      },
    },
    durationHours: 4,
    description: '疲劳↑↑ 压力↑ 长期代价惨重',
  },
  {
    id: 'gaming',
    name: '打游戏',
    emoji: '🎮',
    category: 'entertainment',
    effect: { dopamine: 25, stress: 10, attention: -5, fatigue: 10 },
    dynamicEffect: {
      dopamine: {
        type: 'proportional',
        base: 18,
        factor: 0.3,
      },
      stress: {
        type: 'contextual',
        base: 8,
        factor: 0.15,
        dependsOn: 'attention',
        condition: (m) => m.attention > 50,
      },
      attention: {
        type: 'contextual',
        base: -5,
        factor: -0.15,
        dependsOn: 'dopamine',
        condition: (m) => m.dopamine > 70,
      },
      fatigue: {
        type: 'proportional',
        base: 8,
        factor: 0.1,
      },
    },
    durationHours: 2,
    description: '多巴胺↑↑ 成瘾风险高',
  },
  {
    id: 'socialize',
    name: '社交',
    emoji: '👥',
    category: 'social',
    effect: { dopamine: 15, stress: -10, attention: 5, fatigue: 5 },
    dynamicEffect: {
      dopamine: {
        type: 'proportional',
        base: 12,
        factor: 0.15,
      },
      stress: {
        type: 'contextual',
        base: -10,
        factor: -0.3,
        dependsOn: 'stress',
        condition: (m) => m.stress > 30,
      },
      attention: {
        type: 'proportional',
        base: 5,
        factor: 0.05,
      },
      fatigue: {
        type: 'contextual',
        base: 5,
        factor: 0.1,
        dependsOn: 'fatigue',
        condition: (m) => m.fatigue < 70,
      },
    },
    durationHours: 1.5,
    description: '多巴胺↑ 压力↓ 健康的社交',
  },
];

export const CATEGORY_LABELS: Record<Behavior['category'], string> = {
  entertainment: '娱乐',
  growth: '成长',
  physiology: '生理',
  social: '社交',
};
